name: Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.3'
            laravel: '^9.0'
            testbench: '^7.0'
          - php: '8.3'
            laravel: '^10.0'
            testbench: '^8.0'
          - php: '8.3'
            laravel: '^11.0'
            testbench: '^9.0'
          - php: '8.3'
            laravel: '^12.0'
            testbench: '^10.0'
          - php: '8.4'
            laravel: '^9.0'
            testbench: '^7.0'
          - php: '8.4'
            laravel: '^10.0'
            testbench: '^8.0'
          - php: '8.4'
            laravel: '^11.0'
            testbench: '^9.0'
          - php: '8.4'
            laravel: '^12.0'
            testbench: '^10.0'
    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: none
          ini-values: error_reporting=E_ALL
          extensions: pdo_mysql, sqlite3

      - name: Install dependencies
        run: |
          composer update \
            --with="illuminate/support:${{ matrix.laravel }}" \
            --with="orchestra/testbench:${{ matrix.testbench }}" \
            --prefer-dist \
            --no-interaction \
            --no-progress

      - name: Run tests
        run: composer test
